### ISSUE TITLE
정보현 code review 

### ISSUE THREAD

**Issue by jeongbohyeoun** [PenguinKKIM/kakao-shop-clone#2]
```css
@media (max-width:1700px) {
  /* 일정 크기로 줄어들면 이미지가 겹져져서 뺐습니다 */
  .badge{
    display: none;
  }
}
```

뱃지 부분을 mediaq.css 로 media 쿼리를 따로 사용하셔서 보기 편한것 같습니다. 
앞으로 저도 media 쿼리를 사용할 때 css 파일을 따로 분할해서 적용해야겠다는 생각이 들었습니다.

<br/>

```css
.vid-items__text-right i:hover{
  color: red;
  transform: scale(1.4);
  transition: .2s;
}
```
혹시 이부분의 요소 하트 부분은 hover 효과를 의도하신건지 궁금합니다. 원본사이트보다 더 깔끔한 것 같아서 좋은 것 같습니다. 

<br/>

원본사이트보다 더 좋은 것 같습니다!
